= Metarnoma Native PDF

image:https://github.com/metanorma/mn-native-pdf/workflows/ubuntu/badge.svg["Build Status", link="https://github.com/metanorma/mn-native-pdf/actions?workflow=ubuntu"]
image:https://github.com/metanorma/mn-native-pdf/workflows/macos/badge.svg["Build Status", link="https://github.com/metanorma/mn-native-pdf/actions?workflow=macos"]

The experimental PDF is available here:

* https://metanorma.github.io/mn-native-pdf/iso-24229.pdf[ISO 24229 sample (PDF)]
* https://metanorma.github.io/mn-native-pdf/iso-rice-en.pdf[ISO Rice sample (PDF)]
* https://metanorma.github.io/mn-native-pdf/itu-G.191.pdf[ITU G.191 (PDF)]
* https://metanorma.github.io/mn-native-pdf/itu-G.650.1-201803-v2.pdf[ITU G.650.1-201803-v2 (PDF)]
* https://metanorma.github.io/mn-native-pdf/itu-G.650.1-201803.pdf[ITU G.650.1-201803 (PDF)]
* https://metanorma.github.io/mn-native-pdf/itu-T-Editing-Guidelines-201602.pdf[ITU T-Editing-Guidelines-201602 (PDF)]
* https://metanorma.github.io/mn-native-pdf/itu-T-REC-H.782-201811-I.MSW-E.pdf[ITU T-REC-H.782-201811-I.MSW-E (PDF)]
* https://metanorma.github.io/mn-native-pdf/itu-T-REC-J.1108-201901-P.MSW-E.pdf[ITU T-REC-J.1108-201901-P.MSW-E (PDF)]
* https://metanorma.github.io/mn-native-pdf/itu-T-REC-P.1203-201710-I.MSW-E.pdf[ITU T-REC-P.1203-201710-I.MSW-E (PDF)]


== Purpose

This repository pilots native PDF capabilities of Metnaorma using XML-FO via Apache FOP.


== Installing Build Tools

You will need Apache FOP, `envsubst`, `make` and the Cambria font set.

=== On macOS

[source,sh]
----
# Install `envsubst`
brew install gettext
brew link --force gettext

# Install Apache FOP
brew install fop

# Install Maven
brew install maven

# Install p7zip
brew install p7zip
----

Manually add the Cambria fonts (`cambria.ttf`, `cambriab.ttf`, `cambriai.ttf`, `cambriaz.ttf`) to your `fonts/` directory under this repository, or anywhere else. Point to it using the environment variable `MN_PDF_FONT_PATH`.

e.g.
[source,sh]
----
export MN_PDF_FONT_PATH=$(pwd)/fonts
mkdir -p ${MN_PDF_FONT_PATH}/truetype/vista/

# Install Cambria
pushd $(mktemp -d)
curl -Ls https://www.rmtweb.co.uk/wp-content/uploads/2013/06/Calibri-and-Cambria-Fonts.zip -o cambria.zip
unzip cambria.zip
mkdir -p ${MN_PDF_FONT_PATH}/truetype/vista/
mv ./Calibri\ and\ Cambria\ Fonts/Cambria*.ttf .
mv Cambria.ttf cambria.ttf
mv Cambria\ Bold.ttf cambriab.ttf
mv Cambria\ Italic.ttf cambriai.ttf
mv Cambria\ Bold\ Italic.ttf cambriaz.ttf
mv *.ttf ${MN_PDF_FONT_PATH}/truetype/vista/
popd

# Install FreeSerif
mkdir -p ${MN_PDF_FONT_PATH}/truetype/freefont/

pushd $(mktemp -d)
curl -Ls https://www.fontspace.com/download/13277/e8f09161b1174b2abe9bd65fb8223c48/gnu-freefont_freeserif.zip -o freefont.zip
unzip freefont.zip
mv *.ttf ${MN_PDF_FONT_PATH}/truetype/freefont/
popd

# Install Nanum Gothic
mkdir -p ${MN_PDF_FONT_PATH}/truetype/nanum/

pushd $(mktemp -d)
curl -Ls https://fonts.google.com/download?family=Nanum%20Gothic -o nanum.zip
unzip nanum.zip
mv NanumGothic{-,}Bold.ttf
mv NanumGothic{-,}ExtraBold.ttf
mv NanumGothic-Regular.ttf NanumGothic.ttf
mv *.ttf ${MN_PDF_FONT_PATH}/truetype/nanum/
popd

# Install Droid Sans Fallback
mkdir -p ${MN_PDF_FONT_PATH}/truetype/droid/

pushd ${MN_PDF_FONT_PATH}/truetype/droid/
wget https://github.com/aosp-mirror/platform_frameworks_base/raw/master/data/fonts/DroidSansFallbackFull.ttf
popd

# Install CJK fonts
export MN_PDF_FONT_PATH=${GITHUB_WORKSPACE}/fonts

pushd $(mktemp -d)
curl -Ls https://github.com/Pal3love/Source-Han-TrueType/raw/master/SourceHanSans.7z -o hansans.7z
7za x hansans.7z
mv *.ttc ${MN_PDF_FONT_PATH}/
popd

# Install MS system fonts
mkdir -p ${MN_PDF_FONT_PATH}/truetype/msttcorefonts
ls -alR /System/Library/Fonts
ln -s /System/Library/Fonts/Supplemental/Arial.ttf ${MN_PDF_FONT_PATH}/truetype/msttcorefonts/arial.ttf
ln -s /System/Library/Fonts/Supplemental/Arial\ Bold.ttf ${MN_PDF_FONT_PATH}/truetype/msttcorefonts/arialbd.ttf
ln -s /System/Library/Fonts/Supplemental/Arial\ Italic.ttf ${MN_PDF_FONT_PATH}/truetype/msttcorefonts/ariali.ttf
ln -s /System/Library/Fonts/Supplemental/Arial\ Bold\ Italic.ttf ${MN_PDF_FONT_PATH}/truetype/msttcorefonts/arialbi.ttf
ln -s /System/Library/Fonts/Supplemental/Times\ New\ Roman.ttf ${MN_PDF_FONT_PATH}/truetype/msttcorefonts/times.ttf
ln -s /System/Library/Fonts/Supplemental/Times\ New\ Roman\ Bold.ttf ${MN_PDF_FONT_PATH}/truetype/msttcorefonts/timesbd.ttf
ln -s /System/Library/Fonts/Supplemental/Times\ New\ Roman\ Italic.ttf ${MN_PDF_FONT_PATH}/truetype/msttcorefonts/timesi.ttf
ln -s /System/Library/Fonts/Supplemental/Times\ New\ Roman\ Bold\ Italic.ttf ${MN_PDF_FONT_PATH}/truetype/msttcorefonts/timesbi.ttf
ln -s /System/Library/Fonts/Supplemental/Courier\ New.ttf ${MN_PDF_FONT_PATH}/truetype/msttcorefonts/cour.ttf
ln -s /System/Library/Fonts/Supplemental/Courier\ New\ Italic.ttf ${MN_PDF_FONT_PATH}/truetype/msttcorefonts/couri.ttf
ln -s /System/Library/Fonts/Supplemental/Courier\ New\ Bold.ttf ${MN_PDF_FONT_PATH}/truetype/msttcorefonts/courbd.ttf
ln -s /System/Library/Fonts/Supplemental/Courier\ New\ Bold\ Italic.ttf ${MN_PDF_FONT_PATH}/truetype/msttcorefonts/courbi.ttf

ls -alR ${MN_PDF_FONT_PATH}

----

Building the document is then easy:

[source,sh]
----
export MN_PDF_FONT_PATH=$(pwd)/fonts
make all

# PDFs will be generated as documents/*.pdf
----

=== On Ubuntu Linux

[source,sh]
----
sudo apt-get -y install gettext-base fop cabextract wget

# Install fontforge
sudo apt-get -y install software-properties-common
sudo add-apt-repository ppa:fontforge/fontforge
sudo apt-get update
sudo apt-get -y install fontforge

# Install fonts
sudo apt-get -y install fonts-freefont-ttf fonts-nanum fonts-droid-fallback

# Install MS system fonts
echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections
sudo apt-get install ttf-mscorefonts-installer

# Setup Cambria fonts
curl -Ls https://gist.github.com/maxwelleite/10774746/raw/ttf-vista-fonts-installer.sh | sudo bash
sudo chown -R $(whoami) /usr/share/fonts/
mkdir -p ~/.fonts
cp -a /usr/share/fonts/* ~/.fonts
----

NOTE: While the Cambria fonts can be setup using the very super convenient setup script kindly provided by http://plasmasturm.org[Aristotle Pagaltzis] at http://plasmasturm.org/code/vistafonts-installer/ , we have switched to https://gist.github.com/maxwelleite/10774746/raw/ttf-vista-fonts-installer.sh in order to be able to extract "Cambria Math" from `cambria.ttc` with `fontforge` for math equations.


Building the document is then easy:

[source,sh]
----
export MN_PDF_FONT_PATH=~/.fonts

# Pull submodules
make update-init update-modules

# PDFs will be generated as documents/*.pdf
make all
----


== Copyright

Ribose Inc.
