= Metarnoma Native PDF

image:https://github.com/metanorma/mn-native-pdf/workflows/xml-fo/badge.svg["Build Status", link="https://github.com/metanorma/mn-native-pdf/actions?workflow=xml-fo"]

The experimental PDF is available here:

* https://metanorma.github.io/mn-native-pdf/iso-24229.pdf[ISO 24229 sample (PDF)]


== Purpose

This repository pilots native PDF capabilities of Metnaorma using XML-FO via Apache FOP.


== Installing Build Tools

You will need Apache FOP, `envsubst`, `make` and the Cambria font set.

=== On macOS

[source,sh]
----
# Install `envsubst`
brew install gettext
brew link --force gettext

# Install Apache FOP
brew install fop
----

Manually add the Cambria fonts (`cambria.ttf`, `cambriab.ttf`, `cambriai.ttf`, `cambriaz.ttf`) to your `fonts/` directory under this repository, or anywhere else. Point to it using the environment variable `MN_PDF_FONT_PATH`.

e.g.
[source,sh]
----
mkdir ~/mn-native-pdf/fonts/
cp /tmp/*.ttf ~/mn-native-pdf/fonts/

export MN_PDF_FONT_PATH=~/mn-native-pdf/fonts
export MN_PDF_FONT_PATH=~/src/mn/mn-native-pdf/fonts

# Install FreeSerif
pushd $(mktemp -d)
curl -Ls https://www.fontspace.com/download/13277/e8f09161b1174b2abe9bd65fb8223c48/gnu-freefont_freeserif.zip -o freefont.zip
unzip freefont.zip
mkdir -p ${MN_PDF_FONT_PATH}/truetype/freefont/
mv *.ttf ${MN_PDF_FONT_PATH}/truetype/freefont/
popd

# Install Nanum Gothic
pushd $(mktemp -d)
curl -Ls https://fonts.google.com/download?family=Nanum%20Gothic -o nanum.zip
unzip nanum.zip
mv NanumGothic{-,}Bold.ttf
mv NanumGothic{-,}ExtraBold.ttf
mv NanumGothic{-,}Regular.ttf
mkdir -p ${MN_PDF_FONT_PATH}/truetype/nanum/
mv *.ttf ${MN_PDF_FONT_PATH}/truetype/nanum/
popd

# Install Droid Sans
pushd $(mktemp -d)
curl -Ls https://fonts.google.com/download?family=Droid%20Sans -o droid.zip
unzip droid.zip
mv DroidSans{-,}Regular.ttf
mv DroidSans{-,}Bold.ttf
mkdir -p ${MN_PDF_FONT_PATH}/truetype/droid/
mv *.ttf ${MN_PDF_FONT_PATH}/truetype/droid/
popd
----

Building the document is then easy:

[source,sh]
----
cd ~/mn-native-pdf/
make all

# PDFs will be generated as documents/*.pdf
----

=== On Ubuntu Linux

[source,sh]
----
sudo apt-get -y install gettext-base fop cabextract wget

# Install fontforge
sudo apt-get -y install software-properties-common
sudo add-apt-repository ppa:fontforge/fontforge
sudo apt-get update
sudo apt-get -y install fontforge

# Install fonts
sudo apt-get -y install fonts-freefont-ttf fonts-nanum fonts-droid-fallback

# (If necessary)
echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections
sudo apt-get install ttf-mscorefonts-installer

# Setup Cambria fonts
curl -Ls https://gist.github.com/maxwelleite/10774746/raw/ttf-vista-fonts-installer.sh | sudo bash
sudo chown -R $(whoami) /usr/share/fonts/
mkdir -p ~/.fonts
cp -a /usr/share/fonts/* ~/.fonts
----

NOTE: While the Cambria fonts can be setup using the very super convenient setup script kindly provided by http://plasmasturm.org[Aristotle Pagaltzis] at http://plasmasturm.org/code/vistafonts-installer/ , we have switched to https://gist.github.com/maxwelleite/10774746/raw/ttf-vista-fonts-installer.sh in order to be able to extract "Cambria Math" from `cambria.ttc` with `fontforge` for math equations.


Building the document is then easy:

[source,sh]
----
export MN_PDF_FONT_PATH=~/.fonts

make all
# PDFs will be generated as documents/*.pdf
----


== Copyright

Ribose Inc.
