name: verapdfcheck

#on:
#  workflow_run:
#    workflows: [ubuntu]
#    types:
#      - completed

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Download workflow artifact
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: ubuntu.yml
          workflow_conclusion: success

      - name: Run Docker image veraPDF
        run: |
          docker pull verapdf/rest:latest
          docker run -d -p 8080:8080 -p 8081:8081 -v ./:/home/folder verapdf/rest:latest

      - name: Test Docker image veraPDF
        run: |
          curl http://localhost:8080/api/

      - name: Wait Docker image running
        run: |
          timeout 20s sh -c 'until curl http://localhost:8080/api/ | grep ReleaseDetails; do echo "Waiting until container to be healthy..."; sleep 1; done'
           
    
      - name: Check PDFs using veraPDF
        run: |
          find ./ -type f -name "*.pdf"
          find ./ -type f -name "*.pdf" -exec curl -F "file=@{}" localhost:8080/api/validate/3a -H "Accept:application/xml" \;
          # find ./ -type f -name "*.pdf" -exec curl -F "file=@{}" localhost:8080/api/validate/3a -H "Accept:application/xml" > "{}.verapdf.report.xml" \;
      
      - name: List files
        run: |
          find ./ -type f -name "*.xml"
          