name: xml-fo

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # cabextract for fonts, gettext-base for envsubst
      - name: Setup prerequisites
        run: |
          sudo apt-get -y install gettext-base fop cabextract wget

          # Install fontforge
          sudo apt-get -y install software-properties-common
          sudo add-apt-repository ppa:fontforge/fontforge
          sudo apt-get update
          sudo apt-get -y install fontforge

          # Install fonts
          sudo apt-get -y install fonts-freefont-ttf fonts-nanum fonts-droid-fallback

          # If necessary
          echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections
          sudo apt-get install ttf-mscorefonts-installer


      - name: Setup fonts # i.e. Cambria
        run: |
          curl -Ls https://gist.github.com/maxwelleite/10774746/raw/ttf-vista-fonts-installer.sh | sudo bash
          sudo chown -R $(whoami) /usr/share/fonts/
          mkdir -p ~/.fonts
          cp -a /usr/share/fonts/* ~/.fonts
          ls -l /home/runner
          ls -l ~/.fonts
          ls -l ~/.fonts/truetype
          ls -l ~/.fonts/truetype/freefont
      - uses: actions/checkout@master
      - name: Compile output
        env:
          MN_PDF_FONT_PATH: ~/.fonts
        run: |
          make all
          mv documents published
      - uses: actions/upload-artifact@master
        with:
          name: published
          path: published


  deploy-gh-pages:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@master
    - uses: actions/download-artifact@master
      with:
        name: published
    - name: deploy-to-gh
      env:
        GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
        GH_DEPLOY_KEY: ${{ secrets.GH_DEPLOY_KEY }}
        GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
      run: |
        curl -L https://raw.githubusercontent.com/metanorma/metanorma-build-scripts/master/ghactions-deploy-to-gh-pages.sh | bash
