name: xml-fo

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # cabextract for fonts, gettext-base for envsubst
      - name: Setup prerequisites
        run: |
          sudo apt-get -y install gettext-base fop cabextract
      - name: Setup fonts # i.e. Cambria
        run: |
          mkdir -p ~/.fonts
          curl -Ls http://plasmasturm.org/dl/vistafonts-installer | bash
          ls -l /home/runner
          ls -l ~/.fonts
          ls -l ~/.fonts/truetype
          ls -l ~/.fonts/truetype/freefont
      - uses: actions/checkout@master
      - name: Compile output
        env:
          MN_PDF_FONT_PATH: ~/.fonts
        run: |
          make all
          mv documents published
      - uses: actions/upload-artifact@master
        with:
          name: published
          path: published


  deploy-gh-pages:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@master
    - uses: actions/download-artifact@master
      with:
        name: published
    - name: deploy-to-gh
      env:
        GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
        GH_DEPLOY_KEY: ${{ secrets.GH_DEPLOY_KEY }}
        GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
      run: |
        curl -L https://raw.githubusercontent.com/metanorma/metanorma-build-scripts/master/ghactions-deploy-to-gh-pages.sh | bash
